print ('== DESAFIO 02==')
dia = input ('Qual é o dia do seu aniversário')
mes =  input ('Qual é o mês do seu aniversário')
ano = input ('Qual é o ano do seu aniversário')
print ('Você nasceu no ' +dia+  ' de '  +mes+  ' de '  +ano+ '. Correto')
